## ¿Qué son NumPy y pandas?

![](https://raw.githubusercontent.com/MET4OP-UBA/MET4OP/be8da8567334cbdb85fe6054721edeb50be99e40/clases/clase_05/notas_files/320px-NumPy_logo_2020.svg.png)

Numpy es una biblioteca de Python de código abierto que se utiliza para la informática científica y proporciona una serie de características que permiten a un programador de Python trabajar con matrices y matrices de alto rendimiento.

![](https://raw.githubusercontent.com/MET4OP-UBA/MET4OP/be8da8567334cbdb85fe6054721edeb50be99e40/clases/clase_05/notas_files/320px-Pandas_logo.svg.png)

Pandas es un paquete para la manipulación de datos que usa los objetos DataFrame de R (así como diferentes paquetes de R) en un entorno Python.

Tanto NumPy como pandas se usan a menudo juntos, ya que la biblioteca de pandas depende en gran medida de la matriz NumPy para la implementación de objetos de datos de pandas y comparte muchas de sus características. Además, pandas se basa en la funcionalidad proporcionada por NumPy. Ambas bibliotecas pertenecen a lo que se conoce como la pila SciPy, un conjunto de bibliotecas de Python utilizadas para la informática científica.

In [221]:
import pandas as pd
import numpy as np

### Matrices NumPy

NumPy le permite trabajar con matrices y matrices de alto rendimiento. Su objeto de datos principal es el ndarray, un tipo de matriz de N dimensiones que describe una colección de "elementos" del mismo tipo. Por ejemplo:

In [222]:
np.array ([1, 2, 3, 4, 5]) # definiendo el ndarray

array([1, 2, 3, 4, 5])

Los ndarrays se almacenan de manera más eficiente que las listas de Python y permiten vectorizar las operaciones matemáticas, lo que da como resultado un rendimiento significativamente mayor que con las construcciones de bucle en Python.

Las matrices NumPy permiten seleccionar elementos de matriz, operaciones lógicas, cortar, remodelar, combinar (también conocido como "apilar"), dividir, así como varios métodos numéricos (mínimo, máximo, media, desviación estándar, varianza y más). Todos estos conceptos se pueden aplicar a los objetos pandas, que amplían estas capacidades para proporcionar un medio mucho más rico y expresivo de representar y manipular datos que los que se ofrecen con las matrices NumPy.

## Series

La Serie es el componente principal de los pandas. Una serie representa una matriz indexada etiquetada unidimensional basada en el ndarray NumPy. 

> ``` s = pd.Series(data, index=index) ```

Como una matriz, una serie puede contener cero o más valores de cualquier tipo de datos. Se puede crear e inicializar una serie pasando un valor escalar, un ndarray NumPy, una lista de Python o un Dict de Python como parámetro de datos del constructor de series.

#### A partir de una serie

In [223]:
a = pd.Series([1, 3, 5, np.nan, 6, 8])
a

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

###### Indice generado automáticamente

In [224]:
a.index

RangeIndex(start=0, stop=6, step=1)

#### A partir de un diccionario

In [225]:
d = {'b': 1, 'a': 0, 'c': 2}
pd.Series(d)

b    1
a    0
c    2
dtype: int64

#### A partir de una valor

In [226]:
pd.Series(5., index=['a', 'b', 'c', 'd', 'e'])

a    5.0
b    5.0
c    5.0
d    5.0
e    5.0
dtype: float64

### Diferencias entre ndarrays y objetos de serie

Hay algunas diferencias que vale la pena señalar entre los objetos ndarrays y Series. En primer lugar, se accede a los elementos de las matrices NumPy por su posición entera, comenzando con cero para el primer elemento. Un objeto de la serie pandas es más flexible, ya que puede usar definir su propio índice etiquetado para indexar y acceder a elementos de una matriz. También puede utilizar letras en lugar de números o numerar una matriz en orden descendente en lugar de ascendente. En segundo lugar, alinear datos de diferentes Series y hacer coincidir etiquetas con objetos de Series es más eficiente que usar ndarrays, por ejemplo, tratar con valores perdidos. Si no hay etiquetas coincidentes durante la alineación, pandas devuelve NaN (no ningún número) para que la operación no falle.

# DataFrame

Un DataFrame es una estructura de datos etiquetada bidimensional con columnas de tipos potencialmente diferentes. Puede pensar en ello como una hoja de cálculo o una tabla SQL, o un dict de objetos Series. Generalmente es el objeto de pandas más utilizado. Al igual que Series, DataFrame acepta muchos tipos diferentes de entrada:

- 1D Dict de ndarrays, listas, dict o series

- 2-D numpy.ndarray

- Ndarray estructurado

- Series

- Otro DataFrame

## Creación de un Data-Frame (df)

#### Vía Numpy

In [227]:
dates = pd.date_range('20130101', periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [228]:
df = pd.DataFrame(np.random.randn(6, 4),
                  index=dates,
                  columns=['A', 'B', 'C', 'D'])
df

                   A         B         C         D
2013-01-01 -2.287196 -0.138464  0.906819 -0.318344
2013-01-02  1.236549  0.083646  0.111988  1.210816
2013-01-03 -1.972846 -1.181803  1.622440 -1.224141
2013-01-04  0.313695  0.378203 -1.344556  0.390247
2013-01-05  0.914596 -0.580003  0.894891  0.931474
2013-01-06  2.132521 -1.529082 -0.880954 -0.172500

#### Vía diccionarios de Python

In [229]:
df2 = pd.DataFrame({
    'A': 1.,
    'B': pd.Timestamp('20130102'),
    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
    'D': np.array([3] * 4, dtype='int32'),
    'E': pd.Categorical(["test", "train", "test", "train"]),
    'F': 'foo',
    'G': [1,2,1,2]
})
df2

     A          B    C  D      E    F  G
0  1.0 2013-01-02  1.0  3   test  foo  1
1  1.0 2013-01-02  1.0  3  train  foo  2
2  1.0 2013-01-02  1.0  3   test  foo  1
3  1.0 2013-01-02  1.0  3  train  foo  2

# Tipos de Datos


| Pandas dtype     | Python type     | NumPy type     | Usage|
|-----------------|:---------------------:|:---------------------:|:---------------------:|
| object     | str     | string_, unicode_     | Text|
| int64     | int     | int_, int8, int16, int32, int64, uint8, uint16, uint32, uint64     | Integer numbers|
| float64     | float     | float_, float16, float32, float64     | Floating point numbers|
| bool     | bool     | bool_     | True/False values|
| datetime64     | NA     | datetime64[ns]     | Date and time values|
| timedelta[ns]     | NA     | NA     | Differences between two datetimes|
| category     | NA     | NA     | Finite list of text values |

### Los datos faltantes

* None: el dato faltante de Python

* NaN (Not a number): representación de un número faltante reconocido por todo los sistemas que usan el estandar de de IEEE de coma flotante

> Ver https://jakevdp.github.io/PythonDataScienceHandbook/03.04-missing-values.html

In [230]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [231]:
np.nan + 1

nan

In [232]:
np.nan == '2'

False

In [233]:
np.nan > 0

False

# Importar datos

```python
pd.read_csv(
    '../../dataset/censo2010/hogar.csv',  # file path
    delimiter=',',  # delimitador ',',';','|','\t'
    header=0,  # número de fila como nom de col
    names=None,  # nombre de las columnas (ojo con header)
    index_col=0,  # que col es el índice
    usecols=None,  # que col usar. Ej: [0, 1, 2], ['foo', 'bar', 'baz']
    dtype=None,  # Tipo de col {'a': np.int32, 'b': str} 
    skiprows=None,  # saltear fil al init
    skipfooter=0,  # saltear fil al final
    nrows=None,  # n de fil a leer
    decimal='.',  # separador de decimal. Ej: ',' para EU dat
    quotechar='"',  # char para reconocer str
    #encoding=None,  # para los acentos, ñ, etc
)
```

#### ¿Qué es un archivo .csv?

Los archivos con extensión .csv (comma-separated values) son archivos de texto plano cuyos valores se encuentran separados por un delimitador, por lo general una ",".

La primera fila representa el nombre de nuestras columnas (el header) y las restantes son las filas de nuestro dataframe.

In [234]:
df_in = pd.read_csv('../../dataset/censo2010/hogar.csv')
df_in

,HOGAR_REF_ID,VIVIENDA_REF_ID,NHOG,H05,H06,H07,H08,H09,H10,H11,...,H15,H16,H19A,H19B,H19C,H19D,PROP,INDHAC,TOTPERS,ALGUNBI
0,1,1,1,1,4,1,1,1,1,1,...,2,2,1,2,1,2,5,1,1,0
1,2,1,2,1,1,1,1,1,1,1,...,1,2,1,1,1,1,1,1,1,0
2,3,1,4,1,3,1,1,1,1,1,...,3,5,1,1,1,1,1,1,2,0
3,4,1,6,1,1,1,1,1,1,1,...,3,5,1,1,1,1,5,6,8,1
4,5,2,1,1,1,2,1,1,1,1,...,5,5,1,1,2,1,6,1,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1152594,1152595,1426434,1,1,2,1,1,1,1,1,...,2,3,1,1,1,1,1,1,1,0
1152595,1152596,1426435,1,1,1,1,1,1,1,1,...,1,2,1,2,2,1,1,1,1,0
1152596,1152597,1426436,1,1,1,1,1,1,1,1,...,2,3,1,1,1,1,1,3,3,0
1152597,1152598,1426437,1000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,7,0,2
1152598,1152599,1426438,1000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,7,0,2


```## Revisando un df

In [235]:
df_in.head()

,HOGAR_REF_ID,VIVIENDA_REF_ID,NHOG,H05,H06,H07,H08,H09,H10,H11,...,H15,H16,H19A,H19B,H19C,H19D,PROP,INDHAC,TOTPERS,ALGUNBI
0,1,1,1,1,4,1,1,1,1,1,...,2,2,1,2,1,2,5,1,1,0
1,2,1,2,1,1,1,1,1,1,1,...,1,2,1,1,1,1,1,1,1,0
2,3,1,4,1,3,1,1,1,1,1,...,3,5,1,1,1,1,1,1,2,0
3,4,1,6,1,1,1,1,1,1,1,...,3,5,1,1,1,1,5,6,8,1
4,5,2,1,1,1,2,1,1,1,1,...,5,5,1,1,2,1,6,1,2,1

In [236]:
df_in.tail(3)

,HOGAR_REF_ID,VIVIENDA_REF_ID,NHOG,H05,H06,H07,H08,H09,H10,H11,...,H15,H16,H19A,H19B,H19C,H19D,PROP,INDHAC,TOTPERS,ALGUNBI
1152596,1152597,1426436,1,1,1,1,1,1,1,1,...,2,3,1,1,1,1,1,3,3,0
1152597,1152598,1426437,1000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,7,0,2
1152598,1152599,1426438,1000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,7,0,2

In [237]:
df_in.index

RangeIndex(start=0, stop=1152599, step=1)

In [238]:
type(df_in.index)

pandas.core.indexes.range.RangeIndex

Consultamos todas las columnas disponibles en el datframe

In [239]:
df_in.columns

Index(['HOGAR_REF_ID', 'VIVIENDA_REF_ID', 'NHOG', 'H05', 'H06', 'H07', 'H08',
       'H09', 'H10', 'H11', 'H12', 'H13', 'H14', 'H15', 'H16', 'H19A', 'H19B',
       'H19C', 'H19D', 'PROP', 'INDHAC', 'TOTPERS', 'ALGUNBI'],
      dtype='object')

In [240]:
type(df_in.columns)

pandas.core.indexes.base.Index

Consultamos todos los valores almacenados en el dataset

In [241]:
df_in.values

array([[      1,       1,       1, ...,       1,       1,       0],
       [      2,       1,       2, ...,       1,       1,       0],
       [      3,       1,       4, ...,       1,       2,       0],
       ...,
       [1152597, 1426436,       1, ...,       3,       3,       0],
       [1152598, 1426437,    1000, ...,       7,       0,       2],
       [1152599, 1426438,    1000, ...,       7,       0,       2]],
      shape=(1152599, 23))

In [242]:
type(df_in.values)

numpy.ndarray

Consultamos por la estructura del data frame donde:
0 : filas
1 : columnas

In [243]:
df_in.shape

(1152599, 23)

# Seleccionar (select)

## Subsetting con []

#### Columnas

##### Seleccionar una columna única como una serie
Hay dos components principales de una serie, el índice y la data (valores). **No hay columnas en una serie.**

In [244]:
df_in['ALGUNBI']

0          0
1          0
2          0
3          1
4          1
          ..
1152594    0
1152595    0
1152596    0
1152597    2
1152598    2
Name: ALGUNBI, Length: 1152599, dtype: int64

In [245]:
type(df_in['ALGUNBI'])

pandas.core.series.Series

##### Seleccionar como un DF

Forzamos para llamar un dataframe de 1 columna

In [246]:
df_in[['ALGUNBI']]

         ALGUNBI
0              0
1              0
2              0
3              1
4              1
...          ...
1152594        0
1152595        0
1152596        0
1152597        2
1152598        2

[1152599 rows x 1 columns]

In [247]:
type(df_in[['ALGUNBI']])

pandas.core.frame.DataFrame

##### Seleccionas múltiples colmunas como un DF al pasarle una lista

In [248]:
df_in[['PROP', 'ALGUNBI']]

         PROP  ALGUNBI
0           5        0
1           1        0
2           1        0
3           5        1
4           6        1
...       ...      ...
1152594     1        0
1152595     1        0
1152596     1        0
1152597     0        2
1152598     0        2

[1152599 rows x 2 columns]

##### Cambiar el orden

Simplemente las llammamos en orden invertido

In [249]:
df_in[['ALGUNBI', 'PROP']]

         ALGUNBI  PROP
0              0     5
1              0     1
2              0     1
3              1     5
4              1     6
...          ...   ...
1152594        0     1
1152595        0     1
1152596        0     1
1152597        2     0
1152598        2     0

[1152599 rows x 2 columns]

#### Seleccionar por número de columna

In [250]:
df_in.columns[0] # Devuelve el elemento en la posición 0 en la lista de columnas

'HOGAR_REF_ID'

In [251]:
df_in[df_in.columns[0]] #Devuelve la serie alamacenada en la columna de posición 0

0                1
1                2
2                3
3                4
4                5
            ...
1152594    1152595
1152595    1152596
1152596    1152597
1152597    1152598
1152598    1152599
Name: HOGAR_REF_ID, Length: 1152599, dtype: int64

In [252]:
df_in[[df_in.columns[0]]] #Devuelve un data frame de una columna con la columna de posición 0

         HOGAR_REF_ID
0                   1
1                   2
2                   3
3                   4
4                   5
...               ...
1152594       1152595
1152595       1152596
1152596       1152597
1152597       1152598
1152598       1152599

[1152599 rows x 1 columns]

In [253]:
df_in[df_in.columns[[18, 21]]] #Devuelve un data frame comuesto por una lista de columnas en base a sus posiciones

         H19D  TOTPERS
0           2        1
1           1        1
2           1        2
3           1        8
4           1        2
...       ...      ...
1152594     1        1
1152595     1        1
1152596     1        3
1152597     0        0
1152598     0        0

[1152599 rows x 2 columns]

### Filas

##### x rango

In [254]:
df_in[0:1] #Devuelve todas las filas hasta la fila 0

,HOGAR_REF_ID,VIVIENDA_REF_ID,NHOG,H05,H06,H07,H08,H09,H10,H11,...,H15,H16,H19A,H19B,H19C,H19D,PROP,INDHAC,TOTPERS,ALGUNBI
0,1,1,1,1,4,1,1,1,1,1,...,2,2,1,2,1,2,5,1,1,0

In [255]:
df_in[0:10] #Devuelve todas las filas hasta la fila 9

,HOGAR_REF_ID,VIVIENDA_REF_ID,NHOG,H05,H06,H07,H08,H09,H10,H11,...,H15,H16,H19A,H19B,H19C,H19D,PROP,INDHAC,TOTPERS,ALGUNBI
0,1,1,1,1,4,1,1,1,1,1,...,2,2,1,2,1,2,5,1,1,0
1,2,1,2,1,1,1,1,1,1,1,...,1,2,1,1,1,1,1,1,1,0
2,3,1,4,1,3,1,1,1,1,1,...,3,5,1,1,1,1,1,1,2,0
3,4,1,6,1,1,1,1,1,1,1,...,3,5,1,1,1,1,5,6,8,1
4,5,2,1,1,1,2,1,1,1,1,...,5,5,1,1,2,1,6,1,2,1
5,6,2,2,1,3,1,1,1,1,1,...,3,5,1,1,1,2,5,1,1,1
6,7,2,3,1,2,2,1,1,1,1,...,1,1,1,2,1,1,3,3,1,1
7,8,2,5,1,4,1,1,5,1,1,...,1,2,1,2,1,2,1,3,2,1
8,9,2,7,1,1,1,1,1,1,1,...,5,5,1,1,1,1,6,1,2,1
9,10,3,1,1,2,1,1,1,1,1,...,1,2,1,1,1,1,3,3,2,0

> Operator Overloading
Ciertos operadores poseen un comportamiento diferenciado de a cuerdo a que objetos se los aplica. Por ejemplo, al indexar con $df[*]$, su comportamiento dependerá de si es:
* string: retornará una columna como una serie return a column as a Series
* lista de strings: retornará columnas en forma de DataFrame
* sequencia de enteros / etiquetas: retornará filas (el vector puede ser tanto enteros como etiquetas)
* sequencia de booleanos: retornará filas cuando sean True

## .loc
con loc estamos forzando a que la busqueda se haga en base a etiquetas sean estas nombres de columnas o indices de fila

La indexación mediante .loc selecciona datos por filas o por columnas.
Puede simultaneamente seleccionar filas o columnas y lo hace a través de las etiquetas

#### a series

In [256]:
df_in.loc[1] #Devuelve la fila 1 como serie

HOGAR_REF_ID       2
VIVIENDA_REF_ID    1
NHOG               2
H05                1
H06                1
H07                1
H08                1
H09                1
H10                1
H11                1
H12                1
H13                1
H14                1
H15                1
H16                2
H19A               1
H19B               1
H19C               1
H19D               1
PROP               1
INDHAC             1
TOTPERS            1
ALGUNBI            0
Name: 1, dtype: int64

In [257]:
type(df_in.loc[1])

pandas.core.series.Series

In [258]:
df_in.loc[[1]] #Devuelve la fila 1 como df

,HOGAR_REF_ID,VIVIENDA_REF_ID,NHOG,H05,H06,H07,H08,H09,H10,H11,...,H15,H16,H19A,H19B,H19C,H19D,PROP,INDHAC,TOTPERS,ALGUNBI
1,2,1,2,1,1,1,1,1,1,1,...,1,2,1,1,1,1,1,1,1,0

In [259]:
type(df_in.loc[[1]])

pandas.core.frame.DataFrame

#### Varias Filas

In [260]:
df_in.loc[[1, 2]]

,HOGAR_REF_ID,VIVIENDA_REF_ID,NHOG,H05,H06,H07,H08,H09,H10,H11,...,H15,H16,H19A,H19B,H19C,H19D,PROP,INDHAC,TOTPERS,ALGUNBI
1,2,1,2,1,1,1,1,1,1,1,...,1,2,1,1,1,1,1,1,1,0
2,3,1,4,1,3,1,1,1,1,1,...,3,5,1,1,1,1,1,1,2,0

#### Muchas filas vía Índeces

In [261]:
df_in.loc[1:10] #En este caso si trae el extremo de cierre

,HOGAR_REF_ID,VIVIENDA_REF_ID,NHOG,H05,H06,H07,H08,H09,H10,H11,...,H15,H16,H19A,H19B,H19C,H19D,PROP,INDHAC,TOTPERS,ALGUNBI
1,2,1,2,1,1,1,1,1,1,1,...,1,2,1,1,1,1,1,1,1,0
2,3,1,4,1,3,1,1,1,1,1,...,3,5,1,1,1,1,1,1,2,0
3,4,1,6,1,1,1,1,1,1,1,...,3,5,1,1,1,1,5,6,8,1
4,5,2,1,1,1,2,1,1,1,1,...,5,5,1,1,2,1,6,1,2,1
5,6,2,2,1,3,1,1,1,1,1,...,3,5,1,1,1,2,5,1,1,1
6,7,2,3,1,2,2,1,1,1,1,...,1,1,1,2,1,1,3,3,1,1
7,8,2,5,1,4,1,1,5,1,1,...,1,2,1,2,1,2,1,3,2,1
8,9,2,7,1,1,1,1,1,1,1,...,5,5,1,1,1,1,6,1,2,1
9,10,3,1,1,2,1,1,1,1,1,...,1,2,1,1,1,1,3,3,2,0
10,11,3,3,1,1,1,1,1,1,1,...,1,3,1,2,1,1,5,1,1,0

In [262]:
df_in.loc[:10]

,HOGAR_REF_ID,VIVIENDA_REF_ID,NHOG,H05,H06,H07,H08,H09,H10,H11,...,H15,H16,H19A,H19B,H19C,H19D,PROP,INDHAC,TOTPERS,ALGUNBI
0,1,1,1,1,4,1,1,1,1,1,...,2,2,1,2,1,2,5,1,1,0
1,2,1,2,1,1,1,1,1,1,1,...,1,2,1,1,1,1,1,1,1,0
2,3,1,4,1,3,1,1,1,1,1,...,3,5,1,1,1,1,1,1,2,0
3,4,1,6,1,1,1,1,1,1,1,...,3,5,1,1,1,1,5,6,8,1
4,5,2,1,1,1,2,1,1,1,1,...,5,5,1,1,2,1,6,1,2,1
5,6,2,2,1,3,1,1,1,1,1,...,3,5,1,1,1,2,5,1,1,1
6,7,2,3,1,2,2,1,1,1,1,...,1,1,1,2,1,1,3,3,1,1
7,8,2,5,1,4,1,1,5,1,1,...,1,2,1,2,1,2,1,3,2,1
8,9,2,7,1,1,1,1,1,1,1,...,5,5,1,1,1,1,6,1,2,1
9,10,3,1,1,2,1,1,1,1,1,...,1,2,1,1,1,1,3,3,2,0
10,11,3,3,1,1,1,1,1,1,1,...,1,3,1,2,1,1,5,1,1,0

In [263]:
df_in.loc[10:]

,HOGAR_REF_ID,VIVIENDA_REF_ID,NHOG,H05,H06,H07,H08,H09,H10,H11,...,H15,H16,H19A,H19B,H19C,H19D,PROP,INDHAC,TOTPERS,ALGUNBI
10,11,3,3,1,1,1,1,1,1,1,...,1,3,1,2,1,1,5,1,1,0
11,12,3,6,1,1,1,1,1,1,1,...,5,5,1,1,1,1,6,3,5,0
12,13,4,1,1,1,1,1,1,1,1,...,1,2,1,1,1,2,3,1,1,0
13,14,5,1,2,4,2,1,2,1,1,...,1,2,1,1,1,2,3,1,1,0
14,15,6,1,2,8,2,1,2,1,1,...,6,10,1,1,2,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1152594,1152595,1426434,1,1,2,1,1,1,1,1,...,2,3,1,1,1,1,1,1,1,0
1152595,1152596,1426435,1,1,1,1,1,1,1,1,...,1,2,1,2,2,1,1,1,1,0
1152596,1152597,1426436,1,1,1,1,1,1,1,1,...,2,3,1,1,1,1,1,3,3,0
1152597,1152598,1426437,1000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,7,0,2
1152598,1152599,1426438,1000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,7,0,2

### Subsetear filas y columnas con loc

##### Muchas filas

In [264]:
df_in.loc[[1, 2], ['PROP', 'ALGUNBI']]

   PROP  ALGUNBI
1     1        0
2     1        0

#### Seleccionando todas las filas y algunas columnas

In [265]:
df_in.loc[:, ['PROP', 'ALGUNBI']]

         PROP  ALGUNBI
0           5        0
1           1        0
2           1        0
3           5        1
4           6        1
...       ...      ...
1152594     1        0
1152595     1        0
1152596     1        0
1152597     0        2
1152598     0        2

[1152599 rows x 2 columns]

In [266]:
df_in.loc[:, 'PROP':]

         PROP  INDHAC  TOTPERS  ALGUNBI
0           5       1        1        0
1           1       1        1        0
2           1       1        2        0
3           5       6        8        1
4           6       1        2        1
...       ...     ...      ...      ...
1152594     1       1        1        0
1152595     1       1        1        0
1152596     1       3        3        0
1152597     0       7        0        2
1152598     0       7        0        2

[1152599 rows x 4 columns]

### Accediento al elemento

Todas estas líneas de código devuelven exactamente lo mismo (el valor 1), pero la forma en que llegan a ese resultado (el camino interno que toma Python) es muy diferente.

In [267]:
df_in.loc[1, 'PROP']

np.int64(1)

In [268]:
df_in.loc[:, 'PROP'][1] # Extrae TODA la columna 'PROP' a memoria, luego busca el índice 1.

np.int64(1)

In [269]:
df_in.loc[:, 'PROP'].loc[1] # Extrae columna 'PROP' como Serie, luego aplica .loc[1] sobre ella.

np.int64(1)

In [270]:
df_in.loc[1]['PROP'] # Extrae TODA la fila 1 (con todas sus columnas), luego busca 'PROP'.

np.int64(1)

In [271]:
df_in.loc[1].loc['PROP'] # Extrae fila 1 como Serie, luego aplica .loc['PROP'] sobre ella.

np.int64(1)

#### el elemento en forma de serie

In [272]:
df_in.loc[[1], 'PROP']

1    1
Name: PROP, dtype: int64

In [273]:
type(df_in.loc[[1], 'PROP'])

pandas.core.series.Series

#### el elemento en forma de df

In [274]:
df_in.loc[[1], ['PROP']]

   PROP
1     1

In [275]:
type(df_in.loc[[1], ['PROP']])

pandas.core.frame.DataFrame

# .iloc

Busqueda de elementos basada en indices

In [276]:
df_in.iloc[0]

HOGAR_REF_ID       1
VIVIENDA_REF_ID    1
NHOG               1
H05                1
H06                4
H07                1
H08                1
H09                1
H10                1
H11                1
H12                1
H13                1
H14                1
H15                2
H16                2
H19A               1
H19B               2
H19C               1
H19D               2
PROP               5
INDHAC             1
TOTPERS            1
ALGUNBI            0
Name: 0, dtype: int64

In [277]:
df_in.iloc[[0]]

,HOGAR_REF_ID,VIVIENDA_REF_ID,NHOG,H05,H06,H07,H08,H09,H10,H11,...,H15,H16,H19A,H19B,H19C,H19D,PROP,INDHAC,TOTPERS,ALGUNBI
0,1,1,1,1,4,1,1,1,1,1,...,2,2,1,2,1,2,5,1,1,0

In [278]:
df_in.iloc[:, 18]

0          2
1          1
2          1
3          1
4          1
          ..
1152594    1
1152595    1
1152596    1
1152597    0
1152598    0
Name: H19D, Length: 1152599, dtype: int64

In [279]:
df_in.iloc[:, [18]]

         H19D
0           2
1           1
2           1
3           1
4           1
...       ...
1152594     1
1152595     1
1152596     1
1152597     0
1152598     0

[1152599 rows x 1 columns]

In [280]:
df_in.iloc[[5, 2, 4]]

,HOGAR_REF_ID,VIVIENDA_REF_ID,NHOG,H05,H06,H07,H08,H09,H10,H11,...,H15,H16,H19A,H19B,H19C,H19D,PROP,INDHAC,TOTPERS,ALGUNBI
5,6,2,2,1,3,1,1,1,1,1,...,3,5,1,1,1,2,5,1,1,1
2,3,1,4,1,3,1,1,1,1,1,...,3,5,1,1,1,1,1,1,2,0
4,5,2,1,1,1,2,1,1,1,1,...,5,5,1,1,2,1,6,1,2,1

In [281]:
df_in.iloc[3:5]

,HOGAR_REF_ID,VIVIENDA_REF_ID,NHOG,H05,H06,H07,H08,H09,H10,H11,...,H15,H16,H19A,H19B,H19C,H19D,PROP,INDHAC,TOTPERS,ALGUNBI
3,4,1,6,1,1,1,1,1,1,1,...,3,5,1,1,1,1,5,6,8,1
4,5,2,1,1,1,2,1,1,1,1,...,5,5,1,1,2,1,6,1,2,1

In [282]:
df_in.iloc[3:5, [18, 21]]

   H19D  TOTPERS
3     1        8
4     1        2

In [283]:
df_in.iloc[3:5, 18:21]

   H19D  PROP  INDHAC
3     1     5       6
4     1     6       1

# Seleccionar Donde (where)

### [ ]

#### A mano

In [284]:
df_in_head = df_in.head()

In [285]:
booleano = [False, False, True, True, True]

In [286]:
type(booleano)

list

In [287]:
df_in_head[booleano]

,HOGAR_REF_ID,VIVIENDA_REF_ID,NHOG,H05,H06,H07,H08,H09,H10,H11,...,H15,H16,H19A,H19B,H19C,H19D,PROP,INDHAC,TOTPERS,ALGUNBI
2,3,1,4,1,3,1,1,1,1,1,...,3,5,1,1,1,1,1,1,2,0
3,4,1,6,1,1,1,1,1,1,1,...,3,5,1,1,1,1,5,6,8,1
4,5,2,1,1,1,2,1,1,1,1,...,5,5,1,1,2,1,6,1,2,1

In [288]:
booleano = np.array([False, False, True, True, True])

In [289]:
type(booleano)

numpy.ndarray

In [290]:
df_in_head[booleano]

,HOGAR_REF_ID,VIVIENDA_REF_ID,NHOG,H05,H06,H07,H08,H09,H10,H11,...,H15,H16,H19A,H19B,H19C,H19D,PROP,INDHAC,TOTPERS,ALGUNBI
2,3,1,4,1,3,1,1,1,1,1,...,3,5,1,1,1,1,1,1,2,0
3,4,1,6,1,1,1,1,1,1,1,...,3,5,1,1,1,1,5,6,8,1
4,5,2,1,1,1,2,1,1,1,1,...,5,5,1,1,2,1,6,1,2,1

#### Condiciones simples

##### Usando operaciones lógicas: '<', '>', '==', '>=', '<=', !=

aclaramos que podemos referirnos a una columnas así: .COLUMNA
por ejemplo df_in.PROP

In [291]:
booleano = df_in.ALGUNBI > 0
df_in.loc[booleano]
#df_in.loc[booleano, 'PROP':] # o con delimitación de columnas para ver una versión mas reducida

,HOGAR_REF_ID,VIVIENDA_REF_ID,NHOG,H05,H06,H07,H08,H09,H10,H11,...,H15,H16,H19A,H19B,H19C,H19D,PROP,INDHAC,TOTPERS,ALGUNBI
3,4,1,6,1,1,1,1,1,1,1,...,3,5,1,1,1,1,5,6,8,1
4,5,2,1,1,1,2,1,1,1,1,...,5,5,1,1,2,1,6,1,2,1
5,6,2,2,1,3,1,1,1,1,1,...,3,5,1,1,1,2,5,1,1,1
6,7,2,3,1,2,2,1,1,1,1,...,1,1,1,2,1,1,3,3,1,1
7,8,2,5,1,4,1,1,5,1,1,...,1,2,1,2,1,2,1,3,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1152566,1152567,1426397,1,1,2,1,1,1,1,1,...,1,1,1,2,1,2,3,6,5,1
1152568,1152569,1426399,1,1,2,1,1,1,1,1,...,1,1,1,1,1,2,3,6,4,1
1152574,1152575,1426406,1,1,2,2,1,1,1,1,...,1,1,1,1,1,1,3,6,4,1
1152597,1152598,1426437,1000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,7,0,2
1152598,1152599,1426438,1000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,7,0,2

In [292]:
booleano = df_in.ALGUNBI == 0
df_in.loc[booleano, 'PROP':]

         PROP  INDHAC  TOTPERS  ALGUNBI
0           5       1        1        0
1           1       1        1        0
2           1       1        2        0
9           3       3        2        0
10          5       1        1        0
...       ...     ...      ...      ...
1152592     4       1        1        0
1152593     3       4        3        0
1152594     1       1        1        0
1152595     1       1        1        0
1152596     1       3        3        0

[1081358 rows x 4 columns]

#### Condiciones Múltiples

##### Usando &, | , ~

In [293]:
booleano = ~((df_in.ALGUNBI > 0) & (df_in.PROP == 1))
df_in.loc[booleano, 'PROP':]

         PROP  INDHAC  TOTPERS  ALGUNBI
0           5       1        1        0
1           1       1        1        0
2           1       1        2        0
3           5       6        8        1
4           6       1        2        1
...       ...     ...      ...      ...
1152594     1       1        1        0
1152595     1       1        1        0
1152596     1       3        3        0
1152597     0       7        0        2
1152598     0       7        0        2

[1143353 rows x 4 columns]

In [294]:
booleano = ((df_in.ALGUNBI > 0) | (df_in.PROP != 1))
df_in.loc[booleano, 'PROP':]

         PROP  INDHAC  TOTPERS  ALGUNBI
0           5       1        1        0
3           5       6        8        1
4           6       1        2        1
5           5       1        1        1
6           3       3        1        1
...       ...     ...      ...      ...
1152590     3       3        4        0
1152592     4       1        1        0
1152593     3       4        3        0
1152597     0       7        0        2
1152598     0       7        0        2

[512887 rows x 4 columns]

In [295]:
booleano = (df_in.ALGUNBI > 0) & (df_in.PROP == 1)
df_in[booleano]

,HOGAR_REF_ID,VIVIENDA_REF_ID,NHOG,H05,H06,H07,H08,H09,H10,H11,...,H15,H16,H19A,H19B,H19C,H19D,PROP,INDHAC,TOTPERS,ALGUNBI
7,8,2,5,1,4,1,1,5,1,1,...,1,2,1,2,1,2,1,3,2,1
57,58,45,1,2,2,1,1,1,1,1,...,2,3,1,1,1,1,1,6,8,1
101,102,90,1,2,4,2,1,1,1,2,...,1,1,1,2,1,2,1,5,3,1
109,110,96,1,3,8,2,3,1,2,0,...,1,1,2,2,1,2,1,6,5,1
115,116,100,1,2,4,2,1,1,1,2,...,1,1,1,2,1,2,1,6,7,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1152385,1152386,1426165,1,1,1,1,2,1,1,1,...,2,2,1,2,1,1,1,3,2,1
1152386,1152387,1426166,1,1,1,1,2,1,1,1,...,2,2,1,2,1,1,1,1,1,1
1152387,1152388,1426167,1,1,1,1,2,1,1,1,...,2,2,1,2,1,1,1,5,5,1
1152388,1152389,1426168,1,1,1,1,2,1,1,1,...,2,2,1,2,1,1,1,1,1,1
1152389,1152390,1426169,1,1,1,1,2,1,1,1,...,2,2,1,2,1,1,1,1,1,1

#### Filtrando por ocurrencias: **isin**

In [296]:
df_in[df_in.PROP.isin([1,2]) ]

,HOGAR_REF_ID,VIVIENDA_REF_ID,NHOG,H05,H06,H07,H08,H09,H10,H11,...,H15,H16,H19A,H19B,H19C,H19D,PROP,INDHAC,TOTPERS,ALGUNBI
1,2,1,2,1,1,1,1,1,1,1,...,1,2,1,1,1,1,1,1,1,0
2,3,1,4,1,3,1,1,1,1,1,...,3,5,1,1,1,1,1,1,2,0
7,8,2,5,1,4,1,1,5,1,1,...,1,2,1,2,1,2,1,3,2,1
14,15,6,1,2,8,2,1,2,1,1,...,6,10,1,1,2,1,1,1,1,0
17,18,9,1,1,4,1,1,1,1,1,...,5,5,1,1,1,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1152589,1152590,1426425,1,1,2,1,1,1,1,1,...,2,3,1,1,1,1,1,2,2,0
1152591,1152592,1426429,1,1,2,1,1,1,1,1,...,2,4,1,1,1,1,1,3,5,0
1152594,1152595,1426434,1,1,2,1,1,1,1,1,...,2,3,1,1,1,1,1,1,1,0
1152595,1152596,1426435,1,1,1,1,1,1,1,1,...,1,2,1,2,2,1,1,1,1,0
1152596,1152597,1426436,1,1,1,1,1,1,1,1,...,2,3,1,1,1,1,1,3,3,0

#### Buscando missing values

In [297]:
df_in[ df_in.PROP.isnull() ]

Empty DataFrame
Columns: [HOGAR_REF_ID, VIVIENDA_REF_ID, NHOG, H05, H06, H07, H08, H09, H10, H11, H12, H13, H14, H15, H16, H19A, H19B, H19C, H19D, PROP, INDHAC, TOTPERS, ALGUNBI]
Index: []

[0 rows x 23 columns]

## Usar .loc para seleccior columnas y bools de filas

In [298]:
df_in.loc[df_in.PROP.isin([1,2]), ['PROP','ALGUNBI']]

         PROP  ALGUNBI
1           1        0
2           1        0
7           1        1
14          1        0
17          1        0
...       ...      ...
1152589     1        0
1152591     1        0
1152594     1        0
1152595     1        0
1152596     1        0

[718743 rows x 2 columns]

#### Usar la comparación de dos columnas

In [299]:
df_in.loc[ df_in.PROP > df_in.ALGUNBI ]

,HOGAR_REF_ID,VIVIENDA_REF_ID,NHOG,H05,H06,H07,H08,H09,H10,H11,...,H15,H16,H19A,H19B,H19C,H19D,PROP,INDHAC,TOTPERS,ALGUNBI
0,1,1,1,1,4,1,1,1,1,1,...,2,2,1,2,1,2,5,1,1,0
1,2,1,2,1,1,1,1,1,1,1,...,1,2,1,1,1,1,1,1,1,0
2,3,1,4,1,3,1,1,1,1,1,...,3,5,1,1,1,1,1,1,2,0
3,4,1,6,1,1,1,1,1,1,1,...,3,5,1,1,1,1,5,6,8,1
4,5,2,1,1,1,2,1,1,1,1,...,5,5,1,1,2,1,6,1,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1152592,1152593,1426431,1,1,2,1,1,1,1,1,...,1,2,1,2,2,1,4,1,1,0
1152593,1152594,1426432,1,1,1,1,1,1,1,1,...,2,2,1,1,1,1,3,4,3,0
1152594,1152595,1426434,1,1,2,1,1,1,1,1,...,2,3,1,1,1,1,1,1,1,0
1152595,1152596,1426435,1,1,1,1,1,1,1,1,...,1,2,1,2,2,1,1,1,1,0
1152596,1152597,1426436,1,1,1,1,1,1,1,1,...,2,3,1,1,1,1,1,3,3,0

## ORDEN (Order by)

### Ascendente

In [300]:
df_in.sort_values(['PROP','ALGUNBI'])

,HOGAR_REF_ID,VIVIENDA_REF_ID,NHOG,H05,H06,H07,H08,H09,H10,H11,...,H15,H16,H19A,H19B,H19C,H19D,PROP,INDHAC,TOTPERS,ALGUNBI
27,28,17,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,7,0,2
28,29,18,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,7,0,2
33,34,21,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,7,0,2
34,35,22,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,7,0,2
35,36,23,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,7,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1151462,1151463,1424966,1,2,4,2,1,1,1,1,...,3,3,1,2,2,1,6,5,6,1
1151463,1151464,1424967,1,1,4,1,1,1,1,1,...,3,3,1,1,1,1,6,6,8,1
1151820,1151821,1425430,1,1,2,1,1,1,2,0,...,1,1,1,2,1,2,6,5,3,1
1151821,1151822,1425430,2,1,1,1,1,1,2,0,...,1,1,1,2,1,2,6,6,7,1
1151822,1151823,1425430,3,1,4,2,1,1,2,0,...,1,1,1,2,1,2,6,6,6,1

### Descendente

In [301]:
df_in.sort_values(['PROP','ALGUNBI'], ascending=False)

,HOGAR_REF_ID,VIVIENDA_REF_ID,NHOG,H05,H06,H07,H08,H09,H10,H11,...,H15,H16,H19A,H19B,H19C,H19D,PROP,INDHAC,TOTPERS,ALGUNBI
4,5,2,1,1,1,2,1,1,1,1,...,5,5,1,1,2,1,6,1,2,1
8,9,2,7,1,1,1,1,1,1,1,...,5,5,1,1,1,1,6,1,2,1
25,26,16,1,1,1,1,1,1,1,1,...,3,5,1,1,1,1,6,1,2,1
30,31,19,2,1,1,1,1,1,1,1,...,3,5,1,1,1,1,6,6,8,1
123,124,106,1,2,4,2,1,1,1,1,...,2,2,1,1,2,1,6,6,7,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1150547,1150548,1423792,1000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,7,0,2
1150548,1150549,1423793,1000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,7,0,2
1151377,1151378,1424839,1000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,7,0,2
1152597,1152598,1426437,1000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,7,0,2
1152598,1152599,1426438,1000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,7,0,2

# Contar

### Valores no nulos

In [302]:
df_in.count()

HOGAR_REF_ID       1152599
VIVIENDA_REF_ID    1152599
NHOG               1152599
H05                1152599
H06                1152599
H07                1152599
H08                1152599
H09                1152599
H10                1152599
H11                1152599
H12                1152599
H13                1152599
H14                1152599
H15                1152599
H16                1152599
H19A               1152599
H19B               1152599
H19C               1152599
H19D               1152599
PROP               1152599
INDHAC             1152599
TOTPERS            1152599
ALGUNBI            1152599
dtype: int64

### Cantidad de registros

In [303]:
df_in.shape[0]

1152599

### Cantidad de columnas

In [304]:
df_in.shape[1]

23

### Estructura del df

In [305]:
df_in.shape

(1152599, 23)

# Agrupar por (Group By)

In [306]:
# Agrupamos y luego contamos número de registros en cada agrupamiento
df_in.groupby(['PROP','ALGUNBI']).size()

PROP  ALGUNBI
0     2            2465
1     0          639712
      1            9246
2     0           67111
      1            2674
3     0          294851
      1           48592
4     0           42047
      1            2466
5     0           21368
      1            2425
6     0           16269
      1            3373
dtype: int64

In [307]:
# .count() tambien nos devuelve numero de registros pero en forma de la estructura del data frame
df_in.groupby(['PROP','ALGUNBI']).count()

              HOGAR_REF_ID  VIVIENDA_REF_ID    NHOG     H05     H06     H07  \
PROP ALGUNBI
0    2                2465             2465    2465    2465    2465    2465
1    0              639712           639712  639712  639712  639712  639712
     1                9246             9246    9246    9246    9246    9246
2    0               67111            67111   67111   67111   67111   67111
     1                2674             2674    2674    2674    2674    2674
3    0              294851           294851  294851  294851  294851  294851
     1               48592            48592   48592   48592   48592   48592
4    0               42047            42047   42047   42047   42047   42047
     1                2466             2466    2466    2466    2466    2466
5    0               21368            21368   21368   21368   21368   21368
     1                2425             2425    2425    2425    2425    2425
6    0               16269            16269   16269   16269   16269   16269
     1                3373             3373    3373    3373    3373    3373

                 H08     H09     H10     H11  ...     H13     H14     H15  \
PROP ALGUNBI                                  ...
0    2          2465    2465    2465    2465  ...    2465    2465    2465
1    0        639712  639712  639712  639712  ...  639712  639712  639712
     1          9246    9246    9246    9246  ...    9246    9246    9246
2    0         67111   67111   67111   67111  ...   67111   67111   67111
     1          2674    2674    2674    2674  ...    2674    2674    2674
3    0        294851  294851  294851  294851  ...  294851  294851  294851
     1         48592   48592   48592   48592  ...   48592   48592   48592
4    0         42047   42047   42047   42047  ...   42047   42047   42047
     1          2466    2466    2466    2466  ...    2466    2466    2466
5    0         21368   21368   21368   21368  ...   21368   21368   21368
     1          2425    2425    2425    2425  ...    2425    2425    2425
6    0         16269   16269   16269   16269  ...   16269   16269   16269
     1          3373    3373    3373    3373  ...    3373    3373    3373

                 H16    H19A    H19B    H19C    H19D  INDHAC  TOTPERS
PROP ALGUNBI
0    2          2465    2465    2465    2465    2465    2465     2465
1    0        639712  639712  639712  639712  639712  639712   639712
     1          9246    9246    9246    9246    9246    9246     9246
2    0         67111   67111   67111   67111   67111   67111    67111
     1          2674    2674    2674    2674    2674    2674     2674
3    0        294851  294851  294851  294851  294851  294851   294851
     1         48592   48592   48592   48592   48592   48592    48592
4    0         42047   42047   42047   42047   42047   42047    42047
     1          2466    2466    2466    2466    2466    2466     2466
5    0         21368   21368   21368   21368   21368   21368    21368
     1          2425    2425    2425    2425    2425    2425     2425
6    0         16269   16269   16269   16269   16269   16269    16269
     1          3373    3373    3373    3373    3373    3373     3373

[13 rows x 21 columns]

# Funciones de Agregación

 |    Agregación   |      Descripción      |
 |-----------------|:---------------------:|
 | count()         | Contar el n de casos  |
 | first(), last() | Primer y último item  |
 | mean(), median()| Media, Mediana        |
 | min(), max()    | Mínimo y Máximo       |
 | std(), var()    | Desvio y varianza     |
 | mad()           | Desviación abs mediana|
 | prod()          | Producto de los items |
 | sum()           | Suma de los Casos     |

### Calcular la media por grupo

![](https://pbpython.com/images/groupby-example.png)

In [308]:
# En este caso, se agrupa por solo dos variables y se retorna el data frame completo, agrupado y con la media para cada variable
( df_in
    .groupby(['PROP','ALGUNBI'])
    .mean()
)

               HOGAR_REF_ID  VIVIENDA_REF_ID        NHOG       H05       H06  \
PROP ALGUNBI
0    2        435113.864097    555295.901826  757.646247  0.000000  0.000000
1    0        603795.279263    758350.461350    1.083014  1.039271  1.822239
     1        475890.517737    604263.872485    1.611616  1.395306  2.553861
2    0        569535.949174    718025.700660    1.119638  1.095484  1.901655
     1        442732.551234    563904.281227    1.654824  1.647719  2.965969
3    0        559084.665088    705990.791135    1.149045  1.042364  1.750542
     1        386821.999877    502532.358022    1.818756  1.153606  2.119053
4    0        580057.614170    730560.250648    1.142436  1.066307  1.854211
     1        486273.088808    620033.500811    1.659773  1.401865  2.655312
5    0        551720.709191    696519.829324    1.064302  1.042400  1.687711
     1        506599.113814    644542.320412    1.241237  1.173608  1.987216
6    0        579696.919786    730355.776753    1.267687  1.132891  2.065646
     1        423470.319004    547341.948710    1.592055  1.434628  2.836051

                   H07       H08       H09       H10       H11  ...       H13  \
PROP ALGUNBI                                                    ...
0    2        0.000000  0.000000  0.000000  0.000000  0.000000  ...  0.000000
1    0        1.082889  1.003570  1.004314  1.000000  1.009212  ...  1.010450
     1        1.435864  1.121133  1.039368  1.246052  0.925698  ...  0.871512
2    0        1.151063  1.009626  1.005916  1.000000  1.036432  ...  1.028520
     1        1.644353  1.239342  1.048616  1.207180  1.073298  ...  0.970456
3    0        1.100054  1.011026  1.006264  1.000000  1.008231  ...  1.047573
     1        1.236850  1.320444  1.018131  1.120678  0.929556  ...  1.461064
4    0        1.121554  1.010869  1.005684  1.000000  1.017362  ...  1.043784
     1        1.424169  1.243715  1.032036  1.172749  0.965126  ...  1.148824
5    0        1.101928  1.006131  1.018673  1.000000  1.004118  ...  1.013618
     1        1.176907  1.130722  1.033814  1.058969  0.966186  ...  1.082887
6    0        1.180896  1.025816  1.013031  1.000000  1.042350  ...  1.077325
     1        1.415357  1.357842  1.094278  1.196561  0.960273  ...  1.198636

                   H14       H15       H16      H19A      H19B      H19C  \
PROP ALGUNBI
0    2        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
1    0        1.143344  2.215835  3.422187  1.004671  1.289855  1.148475
     1        2.544019  1.796561  2.276011  1.106100  1.570409  1.138871
2    0        1.424118  2.042303  3.086066  1.013619  1.328441  1.144805
     1        3.408003  1.611818  1.882573  1.186612  1.717277  1.169035
3    0        1.222841  1.630145  2.474643  1.023846  1.247552  1.064266
     1        1.848226  1.202873  1.250514  1.302498  1.742838  1.133149
4    0        1.294123  1.809784  2.774609  1.024282  1.399886  1.187314
     1        2.779805  1.367397  1.554745  1.203974  1.669100  1.186131
5    0        1.172782  1.490406  2.165762  1.015771  1.392643  1.098231
     1        1.583918  1.284124  1.444124  1.098969  1.414845  1.106392
6    0        1.655357  2.057656  3.057656  1.032086  1.431741  1.174319
     1        3.123036  1.418025  1.560629  1.217314  1.699674  1.183813

                  H19D    INDHAC   TOTPERS
PROP ALGUNBI
0    2        0.000000  7.000000  0.000000
1    0        1.062703  2.108658  2.479202
     1        1.484642  4.066083  3.814623
2    0        1.136058  2.301635  2.471577
     1        1.688482  4.586761  4.083396
3    0        1.213467  2.665699  2.295308
     1        1.758541  4.236335  2.464809
4    0        1.158965  2.423597  2.325850
     1        1.647202  4.720195  3.710868
5    0        1.174373  3.384734  2.590416
     1        1.289485  4.657732  3.287010
6    0        1.219805  2.543549  2.676563
     1        1.685147  4.619923  3.601542

[13 rows x 21 columns]

### Calcular medidas resúmenes por grupo

In [309]:
( df_in[['PROP','ALGUNBI','TOTPERS']]       #En este caso primero filtramos las 3 columnas con las que vamos a trabajar
    .groupby(['PROP','ALGUNBI'])            #Luego seleccionamos las variables de agrupamiento
    .agg(['min', 'max', 'mean', 'median'])  #Por ultimo, las operaciones de agregación se aplican a todas las columnas no incluidas en el groupby
)

             TOTPERS
                 min max      mean median
PROP ALGUNBI
0    2             0   0  0.000000    0.0
1    0             1   8  2.479202    2.0
     1             1   8  3.814623    4.0
2    0             1   8  2.471577    2.0
     1             1   8  4.083396    4.0
3    0             1   8  2.295308    2.0
     1             1   8  2.464809    2.0
4    0             1   8  2.325850    2.0
     1             1   8  3.710868    4.0
5    0             1   8  2.590416    2.0
     1             1   8  3.287010    4.0
6    0             1   8  2.676563    2.0
     1             1   8  3.601542    4.0

### Calcular diferentes medidas resúmenes por grupo por variables

In [310]:
( df_in
    .groupby(['PROP','ALGUNBI'])
    .agg({
        'NHOG': ['min', 'max'],
        'TOTPERS':['mean', 'median']
        })
)

             NHOG         TOTPERS
              min   max      mean median
PROP ALGUNBI
0    2          1  1000  0.000000    0.0
1    0          1    46  2.479202    2.0
     1          1    37  3.814623    4.0
2    0          1    36  2.471577    2.0
     1          1    34  4.083396    4.0
3    0          1    48  2.295308    2.0
     1          1    41  2.464809    2.0
4    0          1    38  2.325850    2.0
     1          1    38  3.710868    4.0
5    0          1    24  2.590416    2.0
     1          1    39  3.287010    4.0
6    0          1    30  2.676563    2.0
     1          1    29  3.601542    4.0

# Funciones Lambdas
Funciones anónimas aplicadas a todas las columnas con apply.
Una función lambda es una función corta escrita en una sola línea, pensada para usarse directamente sin darle un nombre

In [311]:
( df_in
    .apply(lambda x: x[x > 2]    #Para cada columna: cuántos valores son mayores que 2
    .count())
)

HOGAR_REF_ID       1152597
VIVIENDA_REF_ID    1152590
NHOG                 26224
H05                   8179
H06                 116010
H07                      0
H08                   1125
H09                   1204
H10                      0
H11                      0
H12                   4579
H13                      0
H14                  89386
H15                 292326
H16                 699073
H19A                     0
H19B                     0
H19C                     0
H19D                     0
PROP                431391
INDHAC              558761
TOTPERS             456218
ALGUNBI                  0
dtype: int64

In [312]:
# Quién puede decir lo que hace esta función Lambda?
( df_in[['H15','H16','PROP','ALGUNBI']]
    .groupby(['PROP','ALGUNBI'])
    .apply(lambda x: (x+0.)/x.sum()*100)
)

C:\Users\manue\AppData\Local\Temp\ipykernel_13616\2349444996.py:4: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: (x+0.)/x.sum()*100)

                           H15       H16      PROP   ALGUNBI
PROP ALGUNBI
0    2       27            NaN       NaN       NaN  0.040568
             28            NaN       NaN       NaN  0.040568
             33            NaN       NaN       NaN  0.040568
             34            NaN       NaN       NaN  0.040568
             35            NaN       NaN       NaN  0.040568
...                        ...       ...       ...       ...
6    1       1151462  0.062722  0.056991  0.029647  0.029647
             1151463  0.062722  0.056991  0.029647  0.029647
             1151820  0.020907  0.018997  0.029647  0.029647
             1151821  0.020907  0.018997  0.029647  0.029647
             1151822  0.020907  0.018997  0.029647  0.029647

[1152599 rows x 4 columns]

## Having
Luego de agrupar y resumir, filtado de filas resultantes

In [313]:
(
    df_in[['PROP','ALGUNBI','TOTPERS']]
    .groupby(['PROP','ALGUNBI'])
    .sum()
    .groupby(['TOTPERS'])
    .filter(lambda x: x['TOTPERS'] > 10000)
)

              TOTPERS
PROP ALGUNBI
1    0        1585975
     1          35270
2    0         165870
     1          10919
3    0         676774
     1         119770
4    0          97795
5    0          55352
6    0          43545
     1          12148

## Top 1 de un grupo
últil para extraer los primeros casos de cada grupo que cumplen una condición

In [314]:
(df_in[['PROP','ALGUNBI','TOTPERS']]
    .sort_values('TOTPERS', ascending=False)
    .groupby(['PROP','ALGUNBI'])
    .head(1)
)

        PROP  ALGUNBI  TOTPERS
199325     1        0        8
722844     3        1        8
722841     3        0        8
722831     6        0        8
555723     2        0        8
555729     1        1        8
556037     4        0        8
555644     2        1        8
555127     4        1        8
271727     5        0        8
555624     6        1        8
863016     5        1        8
924331     0        2        0

# Agregar Filas y Columnas

## Agregar Columnas

In [315]:

df_1 = df_in[['PROP', 'INDHAC']]
df_1

         PROP  INDHAC
0           5       1
1           1       1
2           1       1
3           5       6
4           6       1
...       ...     ...
1152594     1       1
1152595     1       1
1152596     1       3
1152597     0       7
1152598     0       7

[1152599 rows x 2 columns]

In [316]:
df_2 = df_in[['TOTPERS', 'ALGUNBI']]
df_2

         TOTPERS  ALGUNBI
0              1        0
1              1        0
2              2        0
3              8        1
4              2        1
...          ...      ...
1152594        1        0
1152595        1        0
1152596        3        0
1152597        0        2
1152598        0        2

[1152599 rows x 2 columns]

In [317]:
df = pd.concat([df_1,df_2],axis=1,sort=False)
df

         PROP  INDHAC  TOTPERS  ALGUNBI
0           5       1        1        0
1           1       1        1        0
2           1       1        2        0
3           5       6        8        1
4           6       1        2        1
...       ...     ...      ...      ...
1152594     1       1        1        0
1152595     1       1        1        0
1152596     1       3        3        0
1152597     0       7        0        2
1152598     0       7        0        2

[1152599 rows x 4 columns]

## Agregar Filas

In [318]:
df_1 = df_in.iloc[0:3][['PROP', 'INDHAC']]
df_1

   PROP  INDHAC
0     5       1
1     1       1
2     1       1

In [319]:
df_2 = df_in.iloc[3:6][['PROP', 'INDHAC']]
df_2

   PROP  INDHAC
3     5       6
4     6       1
5     5       1

#### Opción 1

In [320]:
df = pd.concat([df_1,df_2],axis=0,sort=False)
df

   PROP  INDHAC
0     5       1
1     1       1
2     1       1
3     5       6
4     6       1
5     5       1

#### Opción 2

In [321]:
df = df_1.append([df_2])
df

AttributeError: 'DataFrame' object has no attribute 'append'

## Transform

transform aplica una operación a cada grupo, pero mantiene el tamaño original del DataFrame.
A diferencia de aggregate, devuelve un valor para cada fila mapeando el resultado del grupo a su posición inicial.

![](https://pbpython.com/images/transform-example.png)

In [ ]:
df_z = (
    df_in[['PROP', 'ALGUNBI', 'TOTPERS']]
    .groupby(['PROP', 'ALGUNBI'])['TOTPERS']
    .transform(lambda x: (x - x.mean()) / x.std())
)
df_z

0         -1.200076
1         -1.084198
2         -0.351236
3          2.791766
4         -0.800045
             ...
1152594   -1.084198
1152595   -1.084198
1152596    0.381725
1152597         NaN
1152598         NaN
Name: TOTPERS, Length: 1152599, dtype: float64

## Multi-Índices

In [ ]:
df = ( df_in[['PROP','ALGUNBI','TOTPERS']]
    .groupby(['PROP','ALGUNBI'])
    .mean()
)
df

               TOTPERS
PROP ALGUNBI
0    2        0.000000
1    0        2.479202
     1        3.814623
2    0        2.471577
     1        4.083396
3    0        2.295308
     1        2.464809
4    0        2.325850
     1        3.710868
5    0        2.590416
     1        3.287010
6    0        2.676563
     1        3.601542

In [ ]:
df.index

MultiIndex([(0, 2),
            (1, 0),
            (1, 1),
            (2, 0),
            (2, 1),
            (3, 0),
            (3, 1),
            (4, 0),
            (4, 1),
            (5, 0),
            (5, 1),
            (6, 0),
            (6, 1)],
           names=['PROP', 'ALGUNBI'])

## Pivot Table

![](https://pbpython.com/images/pivot-table-datasheet.png)

In [ ]:
df_sub = df_in[['PROP', 'ALGUNBI', 'TOTPERS', 'H15', 'H16']].head(15).copy()
df_sub

    PROP  ALGUNBI  TOTPERS  H15  H16
0      5        0        1    2    2
1      1        0        1    1    2
2      1        0        2    3    5
3      5        1        8    3    5
4      6        1        2    5    5
5      5        1        1    3    5
6      3        1        1    1    1
7      1        1        2    1    2
8      6        1        2    5    5
9      3        0        2    1    2
10     5        0        1    1    3
11     6        0        5    5    5
12     3        0        1    1    2
13     3        0        1    1    2
14     1        0        1    6   10

In [ ]:



pivot_censo = pd.pivot_table(
    df_sub, 
    index=['PROP', 'ALGUNBI'],  
    columns=['H15'],            
    values=['TOTPERS'],        
    aggfunc=[np.sum],            
    fill_value=0,               
    margins=True                 
)


pivot_censo

C:\Users\manue\AppData\Local\Temp\ipykernel_13616\3900667100.py:4: FutureWarning: The provided callable <function sum at 0x000002E7F1297F60> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pivot_censo = pd.pivot_table(
C:\Users\manue\AppData\Local\Temp\ipykernel_13616\3900667100.py:4: FutureWarning: The provided callable <function sum at 0x000002E7F1297F60> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pivot_censo = pd.pivot_table(
C:\Users\manue\AppData\Local\Temp\ipykernel_13616\3900667100.py:4: FutureWarning: The provided callable <function sum at 0x000002E7F1297F60> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pivot_censo = pd.pivot_table(

                 sum
             TOTPERS
H15                1  2   3  5  6 All
PROP ALGUNBI
1    0             1  0   2  0  1   4
     1             2  0   0  0  0   2
3    0             4  0   0  0  0   4
     1             1  0   0  0  0   1
5    0             1  1   0  0  0   2
     1             0  0   9  0  0   9
6    0             0  0   0  5  0   5
     1             0  0   0  4  0   4
All                9  1  11  9  1  31

## CrossTabs

![](https://pbpython.com/images/crosstab_cheatsheet.png)

Tabla crusada de valores absolutos

In [ ]:
pd.crosstab(df_in.PROP, df_in.ALGUNBI)

ALGUNBI       0      1     2
PROP
0             0      0  2465
1        639712   9246     0
2         67111   2674     0
3        294851  48592     0
4         42047   2466     0
5         21368   2425     0
6         16269   3373     0

Agregar margenes

In [ ]:
pd.crosstab(df_in.PROP, df_in.ALGUNBI, margins=True, margins_name="Total")

ALGUNBI        0      1     2    Total
PROP
0              0      0  2465     2465
1         639712   9246     0   648958
2          67111   2674     0    69785
3         294851  48592     0   343443
4          42047   2466     0    44513
5          21368   2425     0    23793
6          16269   3373     0    19642
Total    1081358  68776  2465  1152599

Tageando variables de cruce

In [ ]:
pd.crosstab(df_in.PROP, df_in.ALGUNBI, rownames=['Tipo Propiedad'], colnames=[' Alguna necesidad basica insatisfecha'])

 Alguna necesidad basica insatisfecha       0      1     2
Tipo Propiedad
0                                           0      0  2465
1                                      639712   9246     0
2                                       67111   2674     0
3                                      294851  48592     0
4                                       42047   2466     0
5                                       21368   2425     0
6                                       16269   3373     0

Función de agregacíon sobre la tabla cruzada

In [ ]:
pd.crosstab(df_in.PROP, [df_in.ALGUNBI], values=df_in.TOTPERS, aggfunc='mean').round(2).fillna('-')

ALGUNBI     0     1    2
PROP
0           -     -  0.0
1        2.48  3.81    -
2        2.47  4.08    -
3         2.3  2.46    -
4        2.33  3.71    -
5        2.59  3.29    -
6        2.68   3.6    -

Normalización de todos los valores

In [ ]:
pd.crosstab(df_in.PROP, df_in.ALGUNBI, normalize=True).round(2)

ALGUNBI     0     1    2
PROP
0        0.00  0.00  0.0
1        0.56  0.01  0.0
2        0.06  0.00  0.0
3        0.26  0.04  0.0
4        0.04  0.00  0.0
5        0.02  0.00  0.0
6        0.01  0.00  0.0

Normalización de filas

In [ ]:
pd.crosstab(df_in.PROP, df_in.ALGUNBI, normalize='index').round(2)

ALGUNBI     0     1    2
PROP
0        0.00  0.00  1.0
1        0.99  0.01  0.0
2        0.96  0.04  0.0
3        0.86  0.14  0.0
4        0.94  0.06  0.0
5        0.90  0.10  0.0
6        0.83  0.17  0.0

Normalización de columnas

In [ ]:
pd.crosstab(df_in.PROP, df_in.ALGUNBI, normalize='columns').round(2)

ALGUNBI     0     1    2
PROP
0        0.00  0.00  1.0
1        0.59  0.13  0.0
2        0.06  0.04  0.0
3        0.27  0.71  0.0
4        0.04  0.04  0.0
5        0.02  0.04  0.0
6        0.02  0.05  0.0

## Stack

In [ ]:
# Creamos una base con MultiIndex en filas para poder desapilar
df_multi = df_in.sample(30).pivot_table(
    index=['PROP', 'ALGUNBI'], 
    columns=['H15'], 
    values='TOTPERS', 
    aggfunc='sum'
)
df_multi

H15             1     2     3    4
PROP ALGUNBI
1    0        4.0   5.0  20.0  5.0
     1        6.0  10.0   NaN  NaN
2    0        NaN   2.0   2.0  NaN
3    0        2.0  12.0   7.0  NaN
     1        8.0   1.0   NaN  NaN
4    0        NaN   3.0   NaN  NaN

![](https://pandas.pydata.org/pandas-docs/stable/_images/reshaping_stack.png)

In [ ]:
stacked = df_multi.stack()
stacked

PROP  ALGUNBI  H15
1     0        1       4.0
               2       5.0
               3      20.0
               4       5.0
      1        1       6.0
               2      10.0
2     0        2       2.0
               3       2.0
3     0        1       2.0
               2      12.0
               3       7.0
      1        1       8.0
               2       1.0
4     0        2       3.0
dtype: float64

## Unstack
![](https://pandas.pydata.org/pandas-docs/stable/_images/reshaping_unstack.png)

In [ ]:
# ALGUNBI (el nivel más interno de las filas) sube a las columnas
unstacked_default = stacked.unstack()
unstacked_default

H15             1     2     3    4
PROP ALGUNBI
1    0        4.0   5.0  20.0  5.0
     1        6.0  10.0   NaN  NaN
2    0        NaN   2.0   2.0  NaN
3    0        2.0  12.0   7.0  NaN
     1        8.0   1.0   NaN  NaN
4    0        NaN   3.0   NaN  NaN

![](https://pandas.pydata.org/pandas-docs/stable/_images/reshaping_unstack_1.png)

In [ ]:
# Mueve 'ALGUNBI' (posición 1) a las columnas
unstacked_1 = stacked.unstack(1)
# O por nombre: stacked.unstack('ALGUNBI')
unstacked_1

ALGUNBI      0     1
PROP H15
1    1     4.0   6.0
     2     5.0  10.0
     3    20.0   NaN
     4     5.0   NaN
2    2     2.0   NaN
     3     2.0   NaN
3    1     2.0   8.0
     2    12.0   1.0
     3     7.0   NaN
4    2     3.0   NaN

![](https://pandas.pydata.org/pandas-docs/stable/_images/reshaping_unstack_0.png)

In [ ]:
# Mueve 'PROP' (posición 0) a las columnas
unstacked_0 = stacked.unstack(0)
# O por nombre: stacked.unstack('PROP')
unstacked_0

PROP            1    2     3    4
ALGUNBI H15
0       1     4.0  NaN   2.0  NaN
        2     5.0  2.0  12.0  3.0
        3    20.0  2.0   7.0  NaN
        4     5.0  NaN   NaN  NaN
1       1     6.0  NaN   8.0  NaN
        2    10.0  NaN   1.0  NaN

# Joins

## Tablas a Unir

![](media/join-setup_1.png)

In [ ]:
data = {'key': [1, 2, 3], 'value': ['x1', 'x2', 'x3']}
x = pd.DataFrame.from_dict(data)
print("Data frame x")
x

Data frame x

   key value
0    1    x1
1    2    x2
2    3    x3

In [ ]:
data = {'key': [1, 2, 4], 'value': ['y1', 'y2', 'y3']}
y = pd.DataFrame.from_dict(data)
print("data frame y")
y

data frame y

   key value
0    1    y1
1    2    y2
2    4    y3

## Inner join

Esta cláusula busca coincidencias entre 2 tablas, en función a una columna que tienen en común. De tal modo que sólo la intersección se mostrará en los resultados.

![](https://raw.githubusercontent.com/MET4OP-UBA/MET4OP/be8da8567334cbdb85fe6054721edeb50be99e40/clases/clase_05/notas_files/INNER_JOIN.webp)

Veamos un Ejemplo

![](https://raw.githubusercontent.com/MET4OP-UBA/MET4OP/be8da8567334cbdb85fe6054721edeb50be99e40/clases/clase_05/notas_files/join-inner_2.png)

In [ ]:
#inner join in python pandas

inner_join_df= pd.merge(x, y, on='key', how='inner')
inner_join_df

   key value_x value_y
0    1      x1      y1
1    2      x2      y2

## Left Join

A diferencia de un INNER JOIN, donde se busca una intersección respetada por ambas tablas, con LEFT JOIN damos prioridad a la tabla de la izquierda, y buscamos en la tabla derecha. Si no existe ninguna coincidencia para alguna de las filas de la tabla de la izquierda, de igual forma todos los resultados de la primera tabla se muestran.

![](https://raw.githubusercontent.com/MET4OP-UBA/MET4OP/be8da8567334cbdb85fe6054721edeb50be99e40/clases/clase_05/notas_files/LEFT_JOIN.webp)

Veamos un Ejemplo

![](https://raw.githubusercontent.com/MET4OP-UBA/MET4OP/be8da8567334cbdb85fe6054721edeb50be99e40/clases/clase_05/notas_files/left_joint.png)

In [220]:
left_join_df = pd.merge(x, y, on='key', how='left')
left_join_df

   key value_x value_y
0    1      x1      y1
1    2      x2      y2
2    3      x3     NaN

## Right Join

En el caso de RIGHT JOIN la situación es muy similar, pero aquí se da prioridad a la tabla de la derecha.

![](https://raw.githubusercontent.com/MET4OP-UBA/MET4OP/be8da8567334cbdb85fe6054721edeb50be99e40/clases/clase_05/notas_files/RIGHT_JOIN.webp)

Veamos un Ejemplo

![](https://raw.githubusercontent.com/MET4OP-UBA/MET4OP/be8da8567334cbdb85fe6054721edeb50be99e40/clases/clase_05/notas_files/right_joint.png)

In [ ]:
right_join_df = pd.merge(x, y, on='key', how='right')
right_join_df

   key value_x value_y
0    1      x1      y1
1    2      x2      y2
2    4     NaN      y3

## Full Join

Mientras que LEFT JOIN muestra todas las filas de la tabla izquierda, y RIGHT JOIN muestra todas las correspondientes a la tabla derecha, FULL OUTER JOIN (o simplemente FULL JOIN) se encarga de mostrar todas las filas de ambas tablas, sin importar que no existan coincidencias (usará NULL como un valor por defecto para dichos casos).

![](https://raw.githubusercontent.com/MET4OP-UBA/MET4OP/be8da8567334cbdb85fe6054721edeb50be99e40/clases/clase_05/notas_files/FULL_JOIN.webp)

Veamos un Ejemplo

![](https://raw.githubusercontent.com/MET4OP-UBA/MET4OP/be8da8567334cbdb85fe6054721edeb50be99e40/clases/clase_05/notas_files/outer_joint.png)

In [ ]:
outer_join_df = pd.merge(x, y, on='key', how='outer')
outer_join_df

   key value_x value_y
0    1      x1      y1
1    2      x2      y2
2    3      x3     NaN
3    4     NaN      y3

## Relaciones

### Uno a Uno

In [ ]:

data = {'key': [1, 2, 3], 'value': ['x1', 'x2', 'x3']}
x = pd.DataFrame.from_dict(data)
x

   key value
0    1    x1
1    2    x2
2    3    x3

In [ ]:

data = {'key': [1, 2, 3], 'value': ['y1', 'y2', 'y3']}
y = pd.DataFrame.from_dict(data)
y

   key value
0    1    y1
1    2    y2
2    3    y3

In [ ]:
inner_join_df= pd.merge(x, y, on='key', how='inner')
inner_join_df

   key value_x value_y
0    1      x1      y1
1    2      x2      y2
2    3      x3      y3

### Uno a Muchos (o Muchos a Uno)

In [322]:
data = {'key': [1, 2, 2, 1], 'value': ['x1', 'x2', 'x3', "x4"]}
x = pd.DataFrame.from_dict(data)
x

   key value
0    1    x1
1    2    x2
2    2    x3
3    1    x4

In [323]:

data = {'key': [1, 2], 'value': ['y1', 'y2']}
y = pd.DataFrame.from_dict(data)
y

   key value
0    1    y1
1    2    y2

![](https://raw.githubusercontent.com/MET4OP-UBA/MET4OP/be8da8567334cbdb85fe6054721edeb50be99e40/clases/clase_05/notas_files/join-one-to-many_5.png)

In [324]:
inner_join_df= pd.merge(x, y, on='key', how='inner')
inner_join_df

   key value_x value_y
0    1      x1      y1
1    2      x2      y2
2    2      x3      y2
3    1      x4      y1

### Muchos a Muchos

In [ ]:
data = {'key': [1, 2, 2, 3], 'value': ['x1', 'x2', 'x3', "x4"]}
x = pd.DataFrame.from_dict(data)
x

   key value
0    1    x1
1    2    x2
2    2    x3
3    3    x4

In [ ]:
data = {'key': [1, 2, 2, 3], 'value': ['y1', 'y2', 'y3', "y4"]}
y = pd.DataFrame.from_dict(data)
y

   key value
0    1    y1
1    2    y2
2    2    y3
3    3    y4

![](https://raw.githubusercontent.com/MET4OP-UBA/MET4OP/be8da8567334cbdb85fe6054721edeb50be99e40/clases/clase_05/notas_files/join-many-to-many_6.png))

In [ ]:
inner_join_df= pd.merge(x, y, on='key', how='inner')
inner_join_df

   key value_x value_y
0    1      x1      y1
1    2      x2      y2
2    2      x2      y3
3    2      x3      y2
4    2      x3      y3
5    3      x4      y4

## Union all

![](https://raw.githubusercontent.com/MET4OP-UBA/MET4OP/be8da8567334cbdb85fe6054721edeb50be99e40/clases/clase_05/notas_files/unionAll.png)

In [ ]:
data = {'val_0': [1, 2, 2, 3], 'value': ['a1', 'b2', 'c3', "d4"]}
y = pd.DataFrame.from_dict(data)
y

   val_0 value
0      1    a1
1      2    b2
2      2    c3
3      3    d4

In [ ]:
data = {'val_0': [1, 2, 2, 3], 'value': ['a1', 'b2', 'e3', "f4"]}
x = pd.DataFrame.from_dict(data)
x

   val_0 value
0      1    a1
1      2    b2
2      2    e3
3      3    f4

In [ ]:
df_union_all= pd.concat([y, x], ignore_index=True)
df_union_all

   val_0 value
0      1    a1
1      2    b2
2      2    c3
3      3    d4
4      1    a1
5      2    b2
6      2    e3
7      3    f4

### Union

![](https://raw.githubusercontent.com/MET4OP-UBA/MET4OP/be8da8567334cbdb85fe6054721edeb50be99e40/clases/clase_05/notas_files/union.png)

In [ ]:
df_union= pd.concat([x, y],ignore_index=True).drop_duplicates()
df_union

   val_0 value
0      1    a1
1      2    b2
2      2    e3
3      3    f4
6      2    c3
7      3    d4